### ISSUE TITLE
"oh no" turrets

### ISSUE THREAD

**Issue by TenguOnTheTop** [Eschatologue/Heavy-Armaments-Industries#11]
Title, I guess. A lot of turrets are 'oh no'ing for me. I presume it might be because I had an older version of the mod that I proceeded to update?

**Comment by Eschatologue** [comment]
Yes, due to a recent change, i renamed all turrets JSON files. For example, strikeforce.json is now t3-2_shotgun.json. this affects all turrets, and those affected need to be researched once again in the tech tree

**Comment by TenguOnTheTop** [comment]
Apologies, but I think this is a separate issue. 
![image](https://user-images.githubusercontent.com/56941165/106345935-15b9e000-6279-11eb-8e78-1754816913be.png)

It's the same when looking in the build menu, and when placing them down.

**Comment by Eschatologue** [comment]
sorry for the late reply
try manually deleting the mod and reinstalling

**Comment by TenguOnTheTop** [comment]
This fixed it,  closing now
