### ISSUE TITLE
big crash

### ISSUE THREAD

**Issue by josefivanovichstalin** [Eschatologue/Heavy-Armaments-Industries#14]
when i select the multi turret(the turret that have more than one turret) when i try to se more (i) it crashes the game

**Comment by Eschatologue** [comment]
Probably installing younggam/multi-lib will fix it...
Heck, since when this mod has multi-turret???

**Comment by josefivanovichstalin** [comment]
> Probably installing younggam/multi-lib will fix it...
> Heck, since when this mod has multi-turret???

oh sorry it wss from another mod
