### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Dude-324** [Eschatologue/Heavy-Armaments-Industries#15]
the gelatinizer says cryoliquid instead of cryofluid
the combustion compressor says procudes instead of produce, and its description says blast compound instead of pyratite
![Capture](https://user-images.githubusercontent.com/71083621/107546532-74952880-6b9a-11eb-89a1-b5e6d7629d8c.PNG)
![image](https://user-images.githubusercontent.com/71083621/107546618-90003380-6b9a-11eb-93bc-5b34a7969f2f.png)
![image](https://user-images.githubusercontent.com/71083621/107546664-9db5b900-6b9a-11eb-8376-95e38e781335.png)

**Comment by Eschatologue** [comment]
Already committed to the `testing` branch, will be fixed in HAI 2.5
