### ISSUE TITLE
magmatic generator

### ISSUE THREAD

**Issue by Dude-324** [Eschatologue/Heavy-Armaments-Industries#16]
the magmatic generator which is supposed to be an upgraded thermal generator cannot be placed on slag while thermal generators can
![image](https://user-images.githubusercontent.com/71083621/107546939-e8cfcc00-6b9a-11eb-8d4e-156056af8410.png)
![image](https://user-images.githubusercontent.com/71083621/107546980-f2f1ca80-6b9a-11eb-96b5-7925069e5d8f.png)

**Comment by Eschatologue** [comment]
The magmatic generator will remain unplaceable on slag, after testing, it's just way too OP

**Comment by Butterfinger191-gif** [comment]
But. Could you make a version of it for me please? -butterfinger191-gif

-seb scp expert and o5 coucil member

**Comment by Eschatologue** [comment]
in `magmatic-generator.json` change the `"placeableLiquid": false` to `"placeableLiquid": true`. its too OP

**Comment by Butterfinger191-gif** [comment]
Ok ill send it to my mom she knows code

-seb scp expert and o5 coucil member

**Comment by Eschatologue** [comment]
bruh

**Comment by Butterfinger191-gif** [comment]
Just llet me be

-seb scp expert and o5 coucil member
