### ISSUE TITLE
For some reason the mod is "forbidden"

### ISSUE THREAD

**Issue by Butterfinger191-gif** [Eschatologue/Heavy-Armaments-Industries#17]
Can you fix that msg me if you can if not refer this to anuke

**Comment by Eschatologue** [comment]
Can you explain in it details and send a screenshot?

**Comment by Butterfinger191-gif** [comment]
Ok ill get u one also. Sorry for responding so late i forgot about it

-seb scp expert and o5 coucil member

**Comment by Butterfinger191-gif** [comment]
> me like u i noot noot all de time
