### ISSUE TITLE
Hellseeker still cannot be used

### ISSUE THREAD

**Issue by DatOnePlayer** [Eschatologue/Heavy-Armaments-Industries#3]
![Screenshot_20201123-000942_Mindustry](https://user-images.githubusercontent.com/61370548/99910440-952eae80-2d20-11eb-846e-4ffc49b13138.jpg)

This is the newest screenshot

**Comment by DatOnePlayer** [comment]
@Eschatologue

**Comment by Eschatologue** [comment]
It should be working now, thx for letting me know
