### ISSUE TITLE
A new bug?

### ISSUE THREAD

**Issue by DatOnePlayer** [Eschatologue/Heavy-Armaments-Industries#5]
In 118 beta, Sunflare doesn't have a base turret
And cannot be deconstructed
![Screenshot_20201128-190951_Mindustry](https://user-images.githubusercontent.com/61370548/100515311-baeb0600-31ad-11eb-9708-7437e6738b66.jpg)

**Comment by DatOnePlayer** [comment]
@Eschatologue

**Comment by Eschatologue** [comment]
Yes it is a bug and its in the process of being fixed, at this point it would be surprising if things aren't breaking lol

Thank you for letting me know!
You could do a pull request if you know how to fix it faster btw

**Comment by DatOnePlayer** [comment]
Idk lol
