### ISSUE TITLE
Sprite issue with drills

### ISSUE THREAD

**Issue by TenguOnTheTop** [Eschatologue/Heavy-Armaments-Industries#7]
I noticed that the precission drills now become "oh nos" when placed over minable materials. This is purely a visual glitch, and they still work... Other mods also have this issue I've noticed as well. Drills that match existing drills don't seem to have issues, but gigantic ones have their 'center' turn into the placeholder sprite as well

**Comment by Eschatologue** [comment]
This is fixed with 2.2 Update
